
export const GET_IS_OPEN_SIDEBAR = "GET_IS_OPEN_SIDEBAR"
export const SET_SIDEBAR_OPEN = "SET_SIDEBAR_OPEN"
export const SET_FOCUS_MODE = "SET_FOCUS_MODE"
export const GET_IS_FOCUS_MODE = "GET_IS_FOCUS_MODE"
